In [3]:
import torch
from torch.utils.data import Dataset, DataLoader

class MyDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

# Create a dataset
dataset = MyDataset([1, 2, 3, 4, 5])

# Create a dataloader
dataloader = DataLoader(dataset, batch_size=2, shuffle=False)

# Save the dataloader
torch.save(dataloader, './data/dataloader.pkl')

In [4]:
# Load the dataloader
dataloader2 = torch.load('./data/dataloader.pkl')

# Iterate over the dataloader
for batch in dataloader2:
    print(batch)

tensor([1, 2])
tensor([3, 4])
tensor([5])
